### PR TITLE
[17.0][MIG] stock_request_picking_type: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 156579
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/stock-logistics-request/issues/10

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM

**Review by lbarry-apsl — APPROVED** [review]
Works. LGTM

**Pull request merged**
