### PR TITLE
[16.0][MIG] stock_request_purchase

### PR DESCRIPTION
**Pull request by Urvisha-OSI**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Urvisha-OSI To avoid such things, I suggest you to install pre-commit locally before committing:

image

**Comment by florenciafrigieri2** [comment]
Hi @Urvisha-OSI are you going to continue with this PR?

**Comment by victoralmau** [comment]
This PR should be closed in favor of https://github.com/OCA/stock-logistics-request/pull/12.

**Comment by LoisRForgeFlow** [comment]
Closed as it was migrated in https://github.com/OCA/stock-logistics-request/pull/17

**Pull request closed without merging**
