### PR TITLE
[17.0][MIG] stock_request_direction: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 156412
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/stock-logistics-request/issues/10

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
Working good, checked in runboat

**Review by lbarry-apsl — APPROVED** [review]
Reviewed in Runbot. LGTM

**Comment by peluko00** [comment]
Ready for merge @max3903 ?

**Review by max3903 — APPROVED** [review]

**Pull request merged**
