### PR TITLE
[16.0][MIG] stock_request_direction: Migration to 16.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 16.0

cc https://github.com/APSL 153667

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
Working correctly, checked in runboat

**Review by lbarry-apsl — APPROVED** [review]
Works well, tested on Runboat

**Review by celm1990 — APPROVED** [review]
LGTM

**Comment by peluko00** [comment]
Hi @max3903 , is this ready to merge? 
I'm interested in to start migration to v17.

**Comment by peluko00** [comment]
> @max3903 The merge process could not be finalized, because command `twine check odoo_addon_stock_request_direction-16.0.1.0.0.1-py3-none-any.whl` failed with output:
> 
> ```
> Checking odoo_addon_stock_request_direction-16.0.1.0.0.1-py3-none-any.whl: �[31mFAILED�[0m
> �[31mERROR   �[0m `long_description` has syntax errors in markup and would not be        
>          rendered on PyPI.                                                      
>          line : Error: Anonymous hyperlink mismatch: 1 references but 0 targets.
>          See "backrefs" attribute for IDs.                                      
> �[33mWARNING �[0m `long_description_content_type` missing. defaulting to `text/x-rst`.   
> ```

@max3903 i have to do something or it's an error with oca addon?

**Comment by peluko00** [comment]
> /ocabot merge nobump

Can you relaunch again @LoisRForgeFlow please. I fixed the error

**Comment by LoisRForgeFlow** [comment]
sure

/ocabot merge nobump

**Comment by peluko00** [comment]
> sure
> 
> /ocabot merge nobump

Thanks!

**Pull request merged**
