### PR TITLE
[16.0][MIG] stock_request_purchase

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by bruno-zanotti** [comment]
This PR continues https://github.com/oca/stock-logistics-request/pull/5 and https://github.com/OCA/stock-logistics-request/pull/9

**Comment by carolinafernandez-tecnativa** [comment]
Hi, could you please rebase and squash administrative commits?

Thanks!

**Comment by victoralmau** [comment]
`stock_request` is already merged in https://github.com/OCA/stock-logistics-request/pull/13

Can you rebase to check this PR?

Other changes to be done:
- Update the commit history of branch 15.0 (commits are missing)
- Squash administrative commits.
- Unify migration commits into one ([[FIX] resove pre-commit issue + [FIX] stock_request_purchase: test fixs).
- Remove the commit [DON'T MERGE] test-requirements.txt

**Comment by bruno-zanotti** [comment]
Hi @carolinafernandez-tecnativa @victoralmau thanks for the comments, I think everything is done!

**Review by carolinafernandez-tecnativa — APPROVED** [review]
Functional review, LGTM :) Thanks!

**Review by victoralmau — CHANGES_REQUESTED** [review]
There are still v15 commits pending, you will need to update the commit history (some missing commits: https://github.com/OCA/stock-logistics-warehouse/commit/d3f4620c09c92f808c2801eebdfa6d30b53ed45a + https://github.com/OCA/stock-logistics-warehouse/commit/3982786d4898ebc9568cdff2e6ed61c61a90357c + https://github.com/OCA/stock-logistics-warehouse/commit/cbeeff559742e18d343df66b585ff715dfcb4fe2)

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/stock-logistics-request/pull/17

**Pull request closed without merging**
