### PR TITLE
[16.0][MIG] stock request picking type

### PR DESCRIPTION
**Pull request by Urvisha-OSI**

### CODE REVIEW

**Comment by peluko00** [comment]
Please, fix the tests and push again

**Comment by rousseldenis** [comment]
@Urvisha-OSI

**Comment by rousseldenis** [comment]
@peluko00 It seems @Urvisha-OSI is no more active on github. Do you want to reopen your PR and finish the work there ?

**Comment by peluko00** [comment]
> @peluko00 It seems @Urvisha-OSI is no more active on github. Do you want to reopen your PR and finish the work there ?

Finished [here](https://github.com/OCA/stock-logistics-request/pull/21)

**Pull request closed without merging**
