### PR TITLE
[17.0][MIG] stock_request_kanban

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by BT-jmichaud** [comment]
Hello,
What is exactly the status here?

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
I get an error if I try to create a new kanban card without the UoM setting enabled

image

Apart from this, it works as expected :+1:

**Comment by LoisRForgeFlow** [comment]
@JasminSForgeFlow Can you have a look at my comment? I think other than that it looks good.

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow Can you have a look at my comment? I think other than that it looks good.



> @JasminSForgeFlow Can you have a look at my comment? I think other than that it looks good.

Its fixed, Thanks

**Review by LoisRForgeFlow — APPROVED** [review]
It works perfectly now :+1:

**Pull request merged**
