### PR TITLE
[16.0][MIG] stock_request_direction: Migration to 16.0

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@peluko00 You should also preserve commit history.

When doing format patch you should point to the former repo

**Comment by peluko00** [comment]
> @peluko00 You should also preserve commit history.
> 
> When doing format patch you should point to the former repo

How can i do that?
I can't format patch from another repository

**Comment by rousseldenis** [comment]
> > @peluko00 You should also preserve commit history.
> > When doing format patch you should point to the former repo
> 
> How can i do that? I can't format patch from another repository

@peluko00 Yes you can. Locally, you can do `git remote add stock-logistics-warehouse https://github.com/OCA/stock-logistics-warehouse`, then `git fetch stock-logistics-warehouse`, then `git format-patch --keep-subject --stdout <your current repo>/16.0..stock-logistics-warehouse/14.0 -- stock_request_direction  | git am -3 --keep`

**Comment by peluko00** [comment]
> > > @peluko00 You should also preserve commit history.
> > > When doing format patch you should point to the former repo
> > 
> > 
> > How can i do that? I can't format patch from another repository
> 
> @peluko00 Yes you can. Locally, you can do `git remote add stock-logistics-warehouse https://github.com/OCA/stock-logistics-warehouse`, then `git fetch stock-logistics-warehouse`, then `git format-patch --keep-subject --stdout <your current repo>/16.0..stock-logistics-warehouse/14.0 -- stock_request_direction | git am -3 --keep`

Works! Many Thanks Denis!

**Comment by peluko00** [comment]
NEW PR [here](https://github.com/OCA/stock-logistics-request/pull/20)

**Pull request closed without merging**
